---
- name: Ansible Playbook
  gather_facts: false
  hosts: _Env_Test
  become: yes
  tasks:

    - name: Run Shell Command
      command: echo "Hello World"

    - name: Transfer executable script script
      copy: src=/opt/ansible/dockerapp.sh dest=/home/ansible/ mode=0777
         
    - name: Execute the script
      command: sh /home/ansible/dockerapp.sh
      register: hello

    - debug: msg="{{ hello.stdout }}"

    - debug: msg="{{ hello.stderr }}"
